name: Deploy to AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    env:
      JAR_PATH: build/libs/*.jar

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Gradle execute permission
        run: chmod +x gradlew

      - name: Build JAR with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t spring-app .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read EC2 public IP
        id: ec2ip
        run: echo "EC2_HOST=$(cat ec2-ip.txt)" >> $GITHUB_ENV

      - name: Copy JAR, Dockerfile, and start script to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            ${{ env.JAR_PATH }}
            Dockerfile
            scripts/start-app.sh
          target: "~/app"

      - name: SSH and start Spring app on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x ~/app/start-app.sh
            ~/app/start-app.sh